sudo: false
language: python

python: 2.7

install:
  - make venv

script:
  - make compile
  - make test
  - make lint

notifications:
  irc:
    channels:
      - "chat.freenode.net#quill"
    on_success: change
    on_failure: always
    #use_notice: true
    #skip_join: true
