sudo: false
language: python
cache:
  directories:
    - venv
    - vendor/pypy

python: 2.7

install:
  - make venv

matrix:
  fast_finish: true
  include:
    - env: RUN=lint
    - env: RUN=test
    - env: RUN=compile

script:
  - make $RUN RPYTHONFLAGS=--batch

notifications:
  irc:
    channels:
      - "chat.freenode.net#quill"
    on_success: change
    on_failure: always
    #use_notice: true
    #skip_join: true
